# Generated by Django 2.2.4 on 2021-08-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_auto_20210802_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
