# Generated by Django 2.2.4 on 2021-08-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0009_libro_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Estado',
            new_name='estado',
        ),
    ]
